export const en = {
  recent: "Recently added",
  upcoming: "Upcoming",
  playing: "Playing now",
  playingEyebrow: "Now playing",
  carousel: "Media",
  loading: "Loading media",
  empty: "No media to display",
  upcomingEmpty: "Nothing scheduled for now",
  noPlaying: "No active playback",
  noPlayingSecondary: "Your next session will appear here automatically.",
  unavailable: "Jellyfin is currently unavailable",
  jellyfinUnavailable: "Jellyfin unavailable",
  unavailableSecondary: "Waiting for the media service to reconnect.",
  upcomingNotConfigured: "Upcoming media will be available in a future setup phase",
  error: "Unable to load media",
  notConfigured: "The integration is not configured yet",
  stale: "Showing the last available update",
  partial: "Some media could not be displayed",
  staleShort: "Last known data",
  partialShort: "Partial data",
  playingStatus: "Playing",
  pausedStatus: "Paused",
  playbackProgress: "Playback progress",
  watchedSuffix: "watched",
  remainingPrefix: "Remaining",
  sessions: "Playback sessions",
  previousSession: "Previous session",
  nextSession: "Next session",
  session: "Session",
  movie: "Movie",
  series: "Series",
  episode: "Episode",
  pending: "Pending",
  downloaded: "Downloaded",
} as const;
