export const en = {
  recent: "Recently added",
  recentEyebrow: "Recent",
  upcoming: "Upcoming",
  upcomingEyebrow: "Upcoming",
  playing: "Playing now",
  playingEyebrow: "Now playing",
  loading: "Loading media",
  empty: "No media to display",
  upcomingEmpty: "Nothing scheduled for now",
  noPlaying: "No active playback",
  noPlayingSecondary: "Your next session will appear here automatically.",
  unavailable: "Jellyfin is currently unavailable",
  jellyfinUnavailable: "Jellyfin unavailable",
  unavailableSecondary: "Waiting for the media service to reconnect.",
  upcomingNotConfigured: "Upcoming media will be available in a future setup phase",
  error: "Unable to load media",
  configurationNotFound: "Octopus configuration not found",
  configurationNotFoundSecondary: "Edit this card and select an Octopus Media integration.",
  previousConfigurationUnavailable: "Previous configuration (unavailable)",
  notConfigured: "The integration is not configured yet",
  stale: "Showing the last available update",
  partial: "Some media could not be displayed",
  staleShort: "Last known data",
  partialShort: "Partial data",
  playingStatus: "Playing",
  pausedStatus: "Paused",
  playbackProgress: "Playback progress",
  watchedSuffix: "watched",
  remainingPrefix: "Remaining",
  sessions: "Playback sessions",
  previousSession: "Previous session",
  nextSession: "Next session",
  session: "Session",
  movie: "Movie",
  series: "Series",
  episode: "Episode",
  pending: "Pending",
  downloaded: "Downloaded",
  integration: "Integration",
  selectIntegration: "Select an integration",
  contentMode: "Content / mode",
  mode: "Mode",
  layout: "Layout",
  title: "Title",
  height: "Height",
  appearance: "Appearance",
  itemCount: "Item count",
  postersVisible: "Posters visible",
  content: "Content",
  titles: "Titles",
  dates: "Dates",
  ratings: "Ratings",
  badges: "Badges",
  arrows: "Arrows",
  device: "Device",
  user: "User",
  progress: "Progress",
  time: "Time",
  autoScroll: "Auto-scroll",
  autoScrollInterval: "Auto-scroll interval (seconds)",
  appearanceAuto: "Follow Home Assistant",
  appearanceDark: "Dark",
  appearanceLight: "Light",
  preview: "Preview",
  previewWidth: "Preview width",
  previewCard: "Card preview",
  previewUnavailable: "Live preview is unavailable",
  fictionalPreview: "Deterministic preview: titles and images are fictional.",
  previousPosters: "Previous posters",
  nextPosters: "Next posters",
  today: "Today",
  tomorrow: "Tomorrow",
  digital: "Digital",
  physical: "Physical",
  cinema: "Cinema",
} as const;
