import type { en } from "./en";

export const ptBR: Record<keyof typeof en, string> = {
  recent: "Recém-adicionados",
  upcoming: "Em breve",
  upcomingEmpty: "Nada previsto por enquanto",
  playing: "Tocando agora",
  playingEyebrow: "EM REPRODUÇÃO",
  carousel: "Mídia",
  loading: "Carregando mídia",
  empty: "Nenhuma mídia para exibir",
  noPlaying: "Nenhuma reprodução ativa",
  noPlayingSecondary: "Sua próxima sessão aparecerá aqui automaticamente.",
  unavailable: "O Jellyfin está indisponível no momento",
  jellyfinUnavailable: "Jellyfin indisponível",
  unavailableSecondary: "Aguardando o serviço de mídia se reconectar.",
  upcomingNotConfigured:
    "As próximas mídias estarão disponíveis em uma futura fase de configuração",
  error: "Não foi possível carregar a mídia",
  notConfigured: "A integração ainda não está configurada",
  stale: "Exibindo a última atualização disponível",
  partial: "Algumas mídias não puderam ser exibidas",
  staleShort: "Últimos dados válidos",
  partialShort: "Dados parciais",
  playingStatus: "Tocando",
  pausedStatus: "Pausado",
  playbackProgress: "Progresso da reprodução",
  watchedSuffix: "assistido",
  remainingPrefix: "Restam",
  sessions: "Sessões de reprodução",
  previousSession: "Sessão anterior",
  nextSession: "Próxima sessão",
  session: "Sessão",
  movie: "Filme",
  series: "Série",
  episode: "Episódio",
  pending: "Pendente",
  downloaded: "Baixado",
};
