import type { en } from "./en";

export const ptBR: Record<keyof typeof en, string> = {
  recent: "Recém-adicionados",
  recentEyebrow: "Recentes",
  upcoming: "Em breve",
  upcomingEyebrow: "Em breve",
  upcomingEmpty: "Nada previsto por enquanto",
  playing: "Tocando agora",
  playingEyebrow: "EM REPRODUÇÃO",
  loading: "Carregando mídia",
  empty: "Nenhuma mídia para exibir",
  noPlaying: "Nenhuma reprodução ativa",
  noPlayingSecondary: "Sua próxima sessão aparecerá aqui automaticamente.",
  unavailable: "O Jellyfin está indisponível no momento",
  jellyfinUnavailable: "Jellyfin indisponível",
  unavailableSecondary: "Aguardando o serviço de mídia se reconectar.",
  upcomingNotConfigured:
    "As próximas mídias estarão disponíveis em uma futura fase de configuração",
  error: "Não foi possível carregar a mídia",
  configurationNotFound: "Configuração do Octopus não encontrada",
  configurationNotFoundSecondary: "Edite este cartão e selecione uma integração Octopus Media.",
  previousConfigurationUnavailable: "Configuração anterior (indisponível)",
  notConfigured: "A integração ainda não está configurada",
  stale: "Exibindo a última atualização disponível",
  partial: "Algumas mídias não puderam ser exibidas",
  staleShort: "Últimos dados válidos",
  partialShort: "Dados parciais",
  playingStatus: "Tocando",
  pausedStatus: "Pausado",
  playbackProgress: "Progresso da reprodução",
  watchedSuffix: "assistido",
  remainingPrefix: "Restam",
  sessions: "Sessões de reprodução",
  previousSession: "Sessão anterior",
  nextSession: "Próxima sessão",
  session: "Sessão",
  movie: "Filme",
  series: "Série",
  episode: "Episódio",
  pending: "Pendente",
  downloaded: "Baixado",
  integration: "Integração",
  selectIntegration: "Selecione uma integração",
  contentMode: "Conteúdo / modo",
  mode: "Modo",
  layout: "Layout",
  title: "Título",
  height: "Altura",
  appearance: "Aparência",
  itemCount: "Quantidade de itens",
  postersVisible: "Pôsteres visíveis",
  content: "Conteúdo",
  titles: "Títulos",
  dates: "Datas",
  ratings: "Avaliações",
  badges: "Badges",
  arrows: "Setas",
  device: "Dispositivo",
  user: "Usuário",
  progress: "Progresso",
  time: "Tempo",
  autoScroll: "Rolagem automática",
  autoScrollInterval: "Intervalo da rolagem (segundos)",
  appearanceAuto: "Seguir o Home Assistant",
  appearanceDark: "Escuro",
  appearanceLight: "Claro",
  preview: "Prévia",
  previewWidth: "Largura da prévia",
  previewCard: "Prévia do card",
  previewUnavailable: "A prévia ao vivo está indisponível",
  fictionalPreview: "Prévia determinística: títulos e imagens são fictícios.",
  previousPosters: "Pôsteres anteriores",
  nextPosters: "Próximos pôsteres",
  today: "Hoje",
  tomorrow: "Amanhã",
  digital: "Digital",
  physical: "Físico",
  cinema: "Cinema",
};
